
BOOST_BASEDIR := $(MGC_HOME)/shared/pkgs/boost_inhouse/boost_ext
BOOST_149_BASEDIR := $(BOOST_BASEDIR)

BOOST_INCDIRS := $(BOOST_BASEDIR)/include
BOOST_149_INCDIRS := $(BOOST_149_BASEDIR)/include

BOOST_INCLUDES := -isystem$(BOOST_INCDIR)
BOOST_149_INCLUDES := -isystem$(BOOST_149_INCDIRS)

BOOST_LIBDIR := -L$(MGC_HOME)/pkgs/boost/lib
BOOST_149_LIBDIR := -L$(BOOST_149_BASEDIR)/lib
