rm -rf \
   abt \
   build \
   cdf \
   cfg \
   cif \
   connect \
   db \
   dev \
   oap \
   ote \
   otm \
   lcm \
   le \
   nl \
   pel \
   platcdf \
   pref \
   psw \
   rod \
   rtc \
   sample \
   sch \
   skill \
   sl \
   sym \
   techscripting \


cd ../
rm \
   `find ./ -name "moc_*.cpp"` \
   dragon/placer/src/main/plugin/placer.py \
   dragon/placer/src/main/plugin/placer_pywrap.cxx \
   dragon/placer/src/main/plugin/ui_PlacerLayoutsView.h \
   dragon/placer/src/main/plugin/ui_PlacerMainWindow.h \
   dragon/placer/src/main/plugin/ui_PlacerParetoWidget.h \
   nexus/infra/src/frame/commands.c \
   nexus/infra/src/frame/infra_builtin.ample \
   nexus/infra/src/frame/infra_comp.tcl \
   nexus/infra/src/frame/infra_help.xml \
   nexus/infra/src/frame/infra_msg.h \
   nexus/infra/src/frame/infra.py \
   nexus/techmgr/src/util/parseLefProperties_p.cxx \
   nexus/techmgr/src/util/parseLefProperties_p.h \
   osprey/Application/src/PyxisOpen/Chrome/Icons/qrc_icons.cxx \
   osprey/Application/src/PyxisOpen/Functions/ed/ed.py \
   osprey/Application/src/PyxisOpen/Functions/ed/ed_wrap.cxx \
   osprey/Application/src/PyxisOpen/Functions/oap/oap.py \
   osprey/Application/src/PyxisOpen/Functions/oap/oap_wrap.cxx \
   osprey/Application/src/PyxisOpen/Functions/qa_cmds/qap.py \
   osprey/Application/src/PyxisOpen/Functions/qa_cmds/qap_wrap.cxx \
   osprey/Application/src/Services/GuiReplay/gui.py \
   osprey/Application/src/Services/GuiReplay/gui_pywrap.cxx \
   osprey/Application/src/Services/UISvc/pref.py \
   osprey/Application/src/Services/UISvc/pref_wrap.cxx \
   cicd/Domain/src/ServiceLibs/Abutment/python/abt.py \
   cicd/Domain/src/ServiceLibs/Abutment/python/abt_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/CdfSvc/python/platCdf.py \
   cicd/Domain/src/ServiceLibs/CdfSvc/python/platCdf_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/CompIfcScripting/python/cif.py \
   cicd/Domain/src/ServiceLibs/CompIfcScripting/python/cif_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Python/cfg.py \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/cfgParser_l.cxx \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/cfgParser_p.cxx \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/cfgParser_p.h \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Python/cfg_wrap.cxx \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/location.hh \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/position.hh \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Common/stack.hh \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/cfgPropParser_l.cxx \
   cicd/Domain/src/ServiceLibs/DbScripting/python/db.py \
   cicd/Domain/src/ServiceLibs/DbScripting/python/db_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/IpcService/Server/Python/ipc_internal.py \
   cicd/Domain/src/ServiceLibs/IpcService/Server/Python/ipc_internal_wrap.cxx \
   cicd/Domain/src/ServiceLibs/ParamExprLang/location.hh \
   cicd/Domain/src/ServiceLibs/ParamExprLang/pelParser_p.cxx \
   cicd/Domain/src/ServiceLibs/ParamExprLang/pelParser_p.h \
   cicd/Domain/src/ServiceLibs/ParamExprLang/pelScanner_l.cxx \
   cicd/Domain/src/ServiceLibs/ParamExprLang/position.hh \
   cicd/Domain/src/ServiceLibs/ParamExprLang/python/pel.py \
   cicd/Domain/src/ServiceLibs/ParamExprLang/python/pel_wrap.cxx \
   cicd/Domain/src/ServiceLibs/ParamExprLang/stack.hh \
   cicd/Domain/src/ServiceLibs/RodSvc/python/rod.py \
   cicd/Domain/src/ServiceLibs/RodSvc/python/rod_wrap.cxx \
   cicd/Domain/src/ServiceLibs/Scripting/python/sl.py \
   cicd/Domain/src/ServiceLibs/Scripting/python/sl_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/SimEnvSvc/simdb/simdb.py \
   cicd/Domain/src/ServiceLibs/SimEnvSvc/simdb/simdb_wrap.cxx \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/python/skill.py \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/python/skill_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/location.hh \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/position.hh \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/skill_parser_p.cxx \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/skill_parser_p.h \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/skill_scanner_l.cxx \
   cicd/Domain/src/ServiceLibs/SkillParsingSvc/skill/stack.hh \
   cicd/Domain/src/ServiceLibs/Tech/python/otm.py \
   cicd/Domain/src/ServiceLibs/Tech/python/otm_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/TechScripting/python/ots.py \
   cicd/Domain/src/ServiceLibs/TechScripting/python/ots_pywrap.cxx \
   osprey/Plugins/src/CalibreRealTime/python/rtc.py \
   osprey/Plugins/src/CalibreRealTime/python/rtc_wrap.cxx \
   osprey/Plugins/src/Dev/icons/qrc_dev_icons.cxx \
   osprey/Plugins/src/Dev/python/dev.py \
   osprey/Plugins/src/Dev/python/dev_wrap.cxx \
   osprey/Plugins/src/Elaborator/python/lcm.py \
   osprey/Plugins/src/Elaborator/python/lcm_wrap.cxx \
   osprey/Plugins/src/Layout/icons/qrc_le_icons.cxx \
   osprey/Plugins/src/Layout/python/le.py \
   osprey/Plugins/src/Layout/python/le_wrap.cxx \
   osprey/Plugins/src/Netlister/python/nl.py \
   osprey/Plugins/src/Netlister/python/nl_wrap.cxx \
   osprey/Plugins/src/Sample/icons/qrc_sample_icons.cxx \
   osprey/Plugins/src/Sample/python/sample.py \
   osprey/Plugins/src/Sample/python/sample_wrap.cxx \
   osprey/Plugins/src/Schematic/icons/qrc_sch_icons.cxx \
   osprey/Plugins/src/Schematic/python/sch.py \
   osprey/Plugins/src/Schematic/python/sch_wrap.cxx \
   osprey/Plugins/src/Symbol/icons/qrc_sym_icons.cxx \
   osprey/Plugins/src/Symbol/python/sym.py \
   osprey/Plugins/src/Symbol/python/sym_wrap.cxx \
   cicd/Domain/src/ServiceLibs/PinSwappingSvc/python/psw.py \
   cicd/Domain/src/ServiceLibs/PinSwappingSvc/python/psw_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/Connect/python/connect_pywrap.cxx \
   cicd/Domain/src/ServiceLibs/Connect/python/connect.py \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/cfgPropParser_p.cxx \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/cfgPropParser_p.h \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/location.hh \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/position.hh \
   cicd/Domain/src/ServiceLibs/ConfigDbSvc/Prop/stack.hh


